// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: CMD_ESP_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_StartupScreen
void ui_StartupScreen_screen_init(void);
lv_obj_t * ui_StartupScreen;
lv_obj_t * ui_Bar2;
lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t * ui_HomeScreen;
lv_obj_t * ui_Container2;
void ui_event_Image6(lv_event_t * e);
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Container3;
void ui_event_Image7(lv_event_t * e);
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Container4;
void ui_event_Image8(lv_event_t * e);
lv_obj_t * ui_Image8;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Container5;
void ui_event_Image9(lv_event_t * e);
lv_obj_t * ui_Image9;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label40;
lv_obj_t * ui_Label41;
lv_obj_t * ui_Image5;
// CUSTOM VARIABLES

// SCREEN: ui_MeasureScreen
void ui_MeasureScreen_screen_init(void);
lv_obj_t * ui_MeasureScreen;
void ui_event_Image10(lv_event_t * e);
lv_obj_t * ui_Image10;
lv_obj_t * ui_Label5;
void ui_event_Panel1(lv_event_t * e);
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
void ui_event_Panel2(lv_event_t * e);
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Image14;
// CUSTOM VARIABLES

// SCREEN: ui_DistanceScreen
void ui_DistanceScreen_screen_init(void);
lv_obj_t * ui_DistanceScreen;
void ui_event_Image1(lv_event_t * e);
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Label11;
void ui_event_Dropdown1(lv_event_t * e);
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_Label51;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Image20;
// CUSTOM VARIABLES

// SCREEN: ui_AlignScreen
void ui_AlignScreen_screen_init(void);
lv_obj_t * ui_AlignScreen;
void ui_event_Image15(lv_event_t * e);
lv_obj_t * ui_Image15;
lv_obj_t * ui_Label16;
void ui_event_Panel5(lv_event_t * e);
lv_obj_t * ui_Panel5;
void ui_event_Panel6(lv_event_t * e);
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Image18;
// CUSTOM VARIABLES

// SCREEN: ui_OrientationScreen
void ui_OrientationScreen_screen_init(void);
lv_obj_t * ui_OrientationScreen;
void ui_event_Image19(lv_event_t * e);
lv_obj_t * ui_Image19;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Image22;
lv_obj_t * ui_Image21;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label35;
// CUSTOM VARIABLES

// SCREEN: ui_CompassScreen
void ui_CompassScreen_screen_init(void);
lv_obj_t * ui_CompassScreen;
void ui_event_Image23(lv_event_t * e);
lv_obj_t * ui_Image23;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Image24;
lv_obj_t * ui_Label25;
lv_obj_t * ui_Image26;
lv_obj_t * ui_Label36;
lv_obj_t * ui_Label37;
lv_obj_t * ui_Label38;
lv_obj_t * ui_Label39;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Label42;
lv_obj_t * ui_Label43;
lv_obj_t * ui_Label44;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
lv_obj_t * ui_SettingsScreen;
void ui_event_Image27(lv_event_t * e);
lv_obj_t * ui_Image27;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Image28;
lv_obj_t * ui_Label27;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
void ui_event_Panel8(lv_event_t * e);
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Image29;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label46;
lv_obj_t * ui_Image30;
void ui_event_Panel23(lv_event_t * e);
lv_obj_t * ui_Panel23;
lv_obj_t * ui_Panel21;
lv_obj_t * ui_Label53;
// CUSTOM VARIABLES

// SCREEN: ui_AboutScreen
void ui_AboutScreen_screen_init(void);
lv_obj_t * ui_AboutScreen;
void ui_event_Image31(lv_event_t * e);
lv_obj_t * ui_Image31;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Image34;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label31;
// CUSTOM VARIABLES

// SCREEN: ui_DraftScreen
void ui_DraftScreen_screen_init(void);
lv_obj_t * ui_DraftScreen;
void ui_event_Image2(lv_event_t * e);
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Image3;
void ui_event_Panel11(lv_event_t * e);
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Label15;
lv_obj_t * ui_ImgButton1;
lv_obj_t * ui_Label33;
// CUSTOM VARIABLES

// SCREEN: ui_CalScreen
void ui_CalScreen_screen_init(void);
lv_obj_t * ui_CalScreen;
void ui_event_CalBack(lv_event_t * e);
lv_obj_t * ui_CalBack;
lv_obj_t * ui_Calibration;
lv_obj_t * ui_CalPanel;
lv_obj_t * ui_CalInst;
lv_obj_t * ui_CalPara;
lv_obj_t * ui_System;
lv_obj_t * ui_Gyro;
lv_obj_t * ui_Acc;
lv_obj_t * ui_Mag;
lv_obj_t * ui_magIndi;
lv_obj_t * ui_accIndi;
lv_obj_t * ui_gyroIndi;
lv_obj_t * ui_sysIndi;
lv_obj_t * ui_Image30;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Image6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_MeasureScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MeasureScreen_screen_init);
        _ui_screen_delete(&ui_HomeScreen);
    }
}

void ui_event_Image7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_AlignScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_AlignScreen_screen_init);
        _ui_screen_delete(&ui_HomeScreen);
    }
}

void ui_event_Image8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_DraftScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_DraftScreen_screen_init);
        _ui_screen_delete(&ui_HomeScreen);
    }
}

void ui_event_Image9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingsScreen_screen_init);
        _ui_screen_delete(&ui_HomeScreen);
    }
}

void ui_event_Image10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
        _ui_screen_delete(&ui_MeasureScreen);
    }
}

void ui_event_Panel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_DistanceScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_DistanceScreen_screen_init);
        _ui_screen_delete(&ui_MeasureScreen);
    }
}

void ui_event_Panel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_DistanceScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_DistanceScreen_screen_init);
        _ui_screen_delete(&ui_MeasureScreen);
    }
}

void ui_event_Image1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_MeasureScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MeasureScreen_screen_init);
        _ui_screen_delete(&ui_DistanceScreen);
    }
}

void ui_event_Dropdown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Dropdown1, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}

void ui_event_Image15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
        _ui_screen_delete(&ui_AlignScreen);
    }
}

void ui_event_Panel5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_OrientationScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_OrientationScreen_screen_init);
        _ui_screen_delete(&ui_AlignScreen);
    }
}

void ui_event_Panel6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_CompassScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_CompassScreen_screen_init);
        _ui_screen_delete(&ui_AlignScreen);
    }
}

void ui_event_Image19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_AlignScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_AlignScreen_screen_init);
        _ui_screen_delete(&ui_OrientationScreen);
    }
}

void ui_event_Image23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_AlignScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_AlignScreen_screen_init);
        _ui_screen_delete(&ui_CompassScreen);
    }
}

void ui_event_Image27(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
        _ui_screen_delete(&ui_SettingsScreen);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}

void ui_event_Panel8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_CalScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
        _ui_screen_delete(&ui_SettingsScreen);
    }
}

void ui_event_Panel23(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_AboutScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_AboutScreen_screen_init);
        _ui_screen_delete(&ui_SettingsScreen);
    }
}

void ui_event_Image31(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingsScreen_screen_init);
        _ui_screen_delete(&ui_AboutScreen);
    }
}

void ui_event_Image2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_HomeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
        _ui_screen_delete(&ui_DraftScreen);
    }
}

void ui_event_CalBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomeScreen_screen_init);
        _ui_screen_delete(&ui_CalScreen);
    }
}

void ui_event_Panel11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_ImgButton1, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_StartupScreen_screen_init();
    ui_HomeScreen_screen_init();
    ui_MeasureScreen_screen_init();
    ui_DistanceScreen_screen_init();
    ui_AlignScreen_screen_init();
    ui_OrientationScreen_screen_init();
    ui_CompassScreen_screen_init();
    ui_SettingsScreen_screen_init();
    ui_AboutScreen_screen_init();
    ui_DraftScreen_screen_init();
    ui_CalScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_StartupScreen);
}
