// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: CMD_ESP_UI

#ifndef _CMD_ESP_UI_UI_H
#define _CMD_ESP_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_StartupScreen
void ui_StartupScreen_screen_init(void);
extern lv_obj_t * ui_StartupScreen;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_Container2;
void ui_event_Image6(lv_event_t * e);
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container3;
void ui_event_Image7(lv_event_t * e);
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container4;
void ui_event_Image8(lv_event_t * e);
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container5;
void ui_event_Image9(lv_event_t * e);
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Image5;
// CUSTOM VARIABLES

// SCREEN: ui_MeasureScreen
void ui_MeasureScreen_screen_init(void);
extern lv_obj_t * ui_MeasureScreen;
void ui_event_Image10(lv_event_t * e);
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label5;
void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Image14;
// CUSTOM VARIABLES

// SCREEN: ui_DistanceScreen
void ui_DistanceScreen_screen_init(void);
extern lv_obj_t * ui_DistanceScreen;
void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label11;
void ui_event_Dropdown1(lv_event_t * e);
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image20;
// CUSTOM VARIABLES

// SCREEN: ui_AlignScreen
void ui_AlignScreen_screen_init(void);
extern lv_obj_t * ui_AlignScreen;
void ui_event_Image15(lv_event_t * e);
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label16;
void ui_event_Panel5(lv_event_t * e);
extern lv_obj_t * ui_Panel5;
void ui_event_Panel6(lv_event_t * e);
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Image18;
// CUSTOM VARIABLES

// SCREEN: ui_OrientationScreen
void ui_OrientationScreen_screen_init(void);
extern lv_obj_t * ui_OrientationScreen;
void ui_event_Image19(lv_event_t * e);
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label35;
// CUSTOM VARIABLES

// SCREEN: ui_CompassScreen
void ui_CompassScreen_screen_init(void);
extern lv_obj_t * ui_CompassScreen;
void ui_event_Image23(lv_event_t * e);
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_Label44;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
extern lv_obj_t * ui_SettingsScreen;
void ui_event_Image27(lv_event_t * e);
extern lv_obj_t * ui_Image27;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image28;
extern lv_obj_t * ui_Label27;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
void ui_event_Panel8(lv_event_t * e);
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Image29;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Image30;
void ui_event_Panel23(lv_event_t * e);
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Label53;
// CUSTOM VARIABLES

// SCREEN: ui_AboutScreen
void ui_AboutScreen_screen_init(void);
extern lv_obj_t * ui_AboutScreen;
void ui_event_Image31(lv_event_t * e);
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Image34;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label31;
// CUSTOM VARIABLES

// SCREEN: ui_DraftScreen
void ui_DraftScreen_screen_init(void);
extern lv_obj_t * ui_DraftScreen;
void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Image3;
void ui_event_Panel11(lv_event_t * e);
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Label33;
// CUSTOM VARIABLES

// SCREEN: ui_CalScreen
void ui_CalScreen_screen_init(void);
extern lv_obj_t * ui_CalScreen;
void ui_event_CalBack(lv_event_t * e);
extern lv_obj_t * ui_CalBack;
extern lv_obj_t * ui_Calibration;
extern lv_obj_t * ui_CalPanel;
extern lv_obj_t * ui_CalInst;
extern lv_obj_t * ui_CalPara;
extern lv_obj_t * ui_System;
extern lv_obj_t * ui_Gyro;
extern lv_obj_t * ui_Acc;
extern lv_obj_t * ui_Mag;
extern lv_obj_t * ui_magIndi;
extern lv_obj_t * ui_accIndi;
extern lv_obj_t * ui_gyroIndi;
extern lv_obj_t * ui_sysIndi;
extern lv_obj_t * ui_Image30;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_265045193);    // assets/g2181 1 (1).png
LV_IMG_DECLARE(ui_img_group_2_png);    // assets/Group 2.png
LV_IMG_DECLARE(ui_img_group_20_png);    // assets/Group 20.png
LV_IMG_DECLARE(ui_img_group_4_png);    // assets/Group 4.png
LV_IMG_DECLARE(ui_img_group_3_png);    // assets/Group 3.png
LV_IMG_DECLARE(ui_img_arrow_back_png);    // assets/arrow_back.png
LV_IMG_DECLARE(ui_img_group_21_png);    // assets/Group 21.png
LV_IMG_DECLARE(ui_img_group_22_png);    // assets/Group 22.png
LV_IMG_DECLARE(ui_img_265046220);    // assets/g2181 1 (2).png
LV_IMG_DECLARE(ui_img_group_31_png);    // assets/Group 31.png
LV_IMG_DECLARE(ui_img_group_23_png);    // assets/Group 23.png
LV_IMG_DECLARE(ui_img_group_24_png);    // assets/Group 24.png
LV_IMG_DECLARE(ui_img_rectangle_6_png);    // assets/Rectangle 6.png
LV_IMG_DECLARE(ui_img_group_16_png);    // assets/Group 16.png
LV_IMG_DECLARE(ui_img_group_26_png);    // assets/Group 26.png
LV_IMG_DECLARE(ui_img_group_27_png);    // assets/Group 27.png
LV_IMG_DECLARE(ui_img_group_14_png);    // assets/Group 14.png
LV_IMG_DECLARE(ui_img_group_28_png);    // assets/Group 28.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
