// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: CMD_ESP_UI

#include "ui.h"

void ui_CompassScreen_screen_init(void)
{
    ui_CompassScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CompassScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CompassScreen, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CompassScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CompassScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23 = lv_image_create(ui_CompassScreen);
    lv_image_set_src(ui_Image23, &ui_img_arrow_back_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image23, 28);
    lv_obj_set_y(ui_Image23, 12);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image23, 12, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_Image23, lv_color_hex(0x706767), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Image23, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label24 = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 4);
    lv_obj_set_y(ui_Label24, -116);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Compass");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_CompassScreen);
    lv_obj_set_width(ui_Panel15, 160);
    lv_obj_set_height(ui_Panel15, 160);
    lv_obj_set_x(ui_Panel15, 0);
    lv_obj_set_y(ui_Panel15, -14);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel15, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x202420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_CompassScreen);
    lv_obj_set_width(ui_Panel17, 147);
    lv_obj_set_height(ui_Panel17, 1);
    lv_obj_set_x(ui_Panel17, 0);
    lv_obj_set_y(ui_Panel17, -14);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel16 = lv_obj_create(ui_CompassScreen);
    lv_obj_set_width(ui_Panel16, 1);
    lv_obj_set_height(ui_Panel16, 147);
    lv_obj_set_x(ui_Panel16, 0);
    lv_obj_set_y(ui_Panel16, -14);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel14 = lv_obj_create(ui_CompassScreen);
    lv_obj_set_width(ui_Panel14, 120);
    lv_obj_set_height(ui_Panel14, 120);
    lv_obj_set_x(ui_Panel14, 0);
    lv_obj_set_y(ui_Panel14, -14);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel14, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x393C39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x202420), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image24 = lv_image_create(ui_CompassScreen);
    lv_image_set_src(ui_Image24, &ui_img_265046220);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image24, 0);
    lv_obj_set_y(ui_Image24, -24);
    lv_obj_set_align(ui_Image24, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 4);
    lv_obj_set_y(ui_Label25, 83);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "0°");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image26 = lv_image_create(ui_CompassScreen);
    lv_image_set_src(ui_Image26, &ui_img_group_16_png);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image26, 0);
    lv_obj_set_y(ui_Image26, -15);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label36 = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 0);
    lv_obj_set_y(ui_Label36, -61);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "N");
    lv_obj_set_style_text_color(ui_Label36, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label36, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label36, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 0);
    lv_obj_set_y(ui_Label37, 34);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "S");
    lv_obj_set_style_text_color(ui_Label37, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label37, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, 48);
    lv_obj_set_y(ui_Label38, -14);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "E");
    lv_obj_set_style_text_color(ui_Label38, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label38, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, -46);
    lv_obj_set_y(ui_Label39, -14);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "W");
    lv_obj_set_style_text_color(ui_Label39, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label39, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 54);
    lv_obj_set_y(ui_Label34, -59);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "|");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_Label34, 450, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label42 = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, -39);
    lv_obj_set_y(ui_Label42, 34);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "|");
    lv_obj_set_style_text_color(ui_Label42, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label42, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_Label42, 450, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label43 = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, 43);
    lv_obj_set_y(ui_Label43, 34);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "|");
    lv_obj_set_style_text_color(ui_Label43, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label43, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_Label43, -450, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label44 = lv_label_create(ui_CompassScreen);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, -52);
    lv_obj_set_y(ui_Label44, -58);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "|");
    lv_obj_set_style_text_color(ui_Label44, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label44, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_Label44, -450, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image23, ui_event_Image23, LV_EVENT_ALL, NULL);

}
