// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: CMD_ESP_UI

#include "ui.h"

void ui_CalScreen_screen_init(void)
{
    ui_CalScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CalScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CalScreen, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CalScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalBack = lv_image_create(ui_CalScreen);
    lv_image_set_src(ui_CalBack, &ui_img_arrow_back_png);
    lv_obj_set_width(ui_CalBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalBack, 28);
    lv_obj_set_y(ui_CalBack, 12);
    lv_obj_add_flag(ui_CalBack, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_CalBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CalBack, 12, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_CalBack, lv_color_hex(0x706767), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_CalBack, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Calibration = lv_label_create(ui_CalScreen);
    lv_obj_set_width(ui_Calibration, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Calibration, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Calibration, 4);
    lv_obj_set_y(ui_Calibration, -116);
    lv_obj_set_align(ui_Calibration, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Calibration, "Calibration");
    lv_obj_set_style_text_color(ui_Calibration, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Calibration, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Calibration, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalPanel = lv_obj_create(ui_CalScreen);
    lv_obj_set_width(ui_CalPanel, 216);
    lv_obj_set_height(ui_CalPanel, 67);
    lv_obj_set_x(ui_CalPanel, 0);
    lv_obj_set_y(ui_CalPanel, -54);
    lv_obj_set_align(ui_CalPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CalPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CalPanel, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CalPanel, lv_color_hex(0x222020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CalPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CalPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_CalPanel, 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_CalPanel, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_CalPanel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_CalPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_CalPanel, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_CalInst = lv_label_create(ui_CalPanel);
    lv_obj_set_width(ui_CalInst, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalInst, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CalInst, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CalInst, "Rotate the device in\nloop to calibrate.");
    lv_obj_set_style_text_color(ui_CalInst, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalInst, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CalInst, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalPara = lv_obj_create(ui_CalScreen);
    lv_obj_set_width(ui_CalPara, 223);
    lv_obj_set_height(ui_CalPara, 106);
    lv_obj_set_x(ui_CalPara, 0);
    lv_obj_set_y(ui_CalPara, 40);
    lv_obj_set_align(ui_CalPara, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CalPara, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CalPara, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CalPara, lv_color_hex(0x222020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalPara, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CalPara, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CalPara, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CalPara, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CalPara, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CalPara, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CalPara, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_CalPara, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CalPara, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_CalPara, 14, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(ui_CalPara, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_CalPara, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(ui_CalPara, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_CalPara, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_System = lv_label_create(ui_CalPara);
    lv_obj_set_width(ui_System, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_System, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_System, 0);
    lv_obj_set_y(ui_System, 6);
    lv_label_set_text(ui_System, "System");
    lv_obj_set_style_text_color(ui_System, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_System, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_System, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gyro = lv_label_create(ui_CalPara);
    lv_obj_set_width(ui_Gyro, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Gyro, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Gyro, 0);
    lv_obj_set_y(ui_Gyro, 25);
    lv_label_set_text(ui_Gyro, "Gyro");
    lv_obj_set_style_text_color(ui_Gyro, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Gyro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Gyro, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Acc = lv_label_create(ui_CalPara);
    lv_obj_set_width(ui_Acc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Acc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Acc, -54);
    lv_obj_set_y(ui_Acc, 14);
    lv_obj_set_align(ui_Acc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Acc, "Accelerometer\n");
    lv_obj_set_style_text_color(ui_Acc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Acc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Acc, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mag = lv_label_create(ui_CalPara);
    lv_obj_set_width(ui_Mag, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mag, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mag, -55);
    lv_obj_set_y(ui_Mag, 33);
    lv_obj_set_align(ui_Mag, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mag, "Magnetometer\n");
    lv_obj_set_style_text_color(ui_Mag, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Mag, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Mag, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_magIndi = lv_bar_create(ui_CalPara);
    lv_bar_set_value(ui_magIndi, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_magIndi, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_magIndi, 89);
    lv_obj_set_height(ui_magIndi, 3);
    lv_obj_set_x(ui_magIndi, -3);
    lv_obj_set_y(ui_magIndi, 71);
    lv_obj_set_align(ui_magIndi, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_magIndi, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_magIndi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_magIndi, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_magIndi, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_magIndi, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_magIndi,
                                                                                              lv_obj_get_style_pad_right(ui_magIndi, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_accIndi = lv_bar_create(ui_CalPara);
    lv_bar_set_value(ui_accIndi, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_accIndi, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_accIndi, 89);
    lv_obj_set_height(ui_accIndi, 3);
    lv_obj_set_x(ui_accIndi, -3);
    lv_obj_set_y(ui_accIndi, 52);
    lv_obj_set_align(ui_accIndi, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_accIndi, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_accIndi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_accIndi, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_accIndi, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_accIndi, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_accIndi,
                                                                                              lv_obj_get_style_pad_right(ui_accIndi, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_gyroIndi = lv_bar_create(ui_CalPara);
    lv_bar_set_value(ui_gyroIndi, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_gyroIndi, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_gyroIndi, 89);
    lv_obj_set_height(ui_gyroIndi, 3);
    lv_obj_set_x(ui_gyroIndi, -3);
    lv_obj_set_y(ui_gyroIndi, 32);
    lv_obj_set_align(ui_gyroIndi, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_gyroIndi, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gyroIndi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_gyroIndi, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gyroIndi, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_gyroIndi, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_gyroIndi,
                                                                                               lv_obj_get_style_pad_right(ui_gyroIndi, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_sysIndi = lv_bar_create(ui_CalPara);
    lv_bar_set_value(ui_sysIndi, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_sysIndi, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_sysIndi, 89);
    lv_obj_set_height(ui_sysIndi, 3);
    lv_obj_set_x(ui_sysIndi, -3);
    lv_obj_set_y(ui_sysIndi, 12);
    lv_obj_set_align(ui_sysIndi, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_sysIndi, lv_color_hex(0x4A4A4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sysIndi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sysIndi, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sysIndi, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_sysIndi, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_sysIndi,
                                                                                              lv_obj_get_style_pad_right(ui_sysIndi, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Image30 = lv_image_create(ui_CalScreen);
    lv_image_set_src(ui_Image30, &ui_img_265046220);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image30, 0);
    lv_obj_set_y(ui_Image30, -24);
    lv_obj_set_align(ui_Image30, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_CalBack, ui_event_CalBack, LV_EVENT_ALL, NULL);

}
